rootPageId: 3
base: 'https://t3events-t9.ddev.site/'
baseVariants: {  }
languages:
  -
    title: english
    enabled: true
    languageId: '0'
    base: /
    typo3Language: default
    locale: en_US.UTF-8
    iso-639-1: en
    navigationTitle: ''
    hreflang: ''
    direction: ''
    flag: global
errorHandling: {  }
routes: {  }
